/* DDL FOR SPRING23_S003_7_UTA_MARKETPLACE*/
/* NOT USING BIGINT OR NUMERIC FOR PHONE NUMBER IN ORDER TO ADD SUPPORT FOR INTERNATIONAL DIALING CODES */

CREATE TABLE SPRING23_S003_7_ACCOUNT (
    USERNAME VARCHAR(30) PRIMARY KEY,
    EMAIL VARCHAR(30) UNIQUE,
    PHONE_NUMBER VARCHAR(10) UNIQUE,
    FIRST_NAME VARCHAR(30),
    LAST_NAME VARCHAR(30),
    PASSWORD  VARCHAR(30)
);

CREATE TABLE SPRING23_S003_7_ADMIN(
    ADMIN_USERNAME VARCHAR(30) PRIMARY KEY,
    SSN VARCHAR(20) UNIQUE,
    SALARY VARCHAR(10),
    ADDRESS VARCHAR(100),
    FOREIGN KEY (ADMIN_USERNAME) REFERENCES SPRING23_S003_7_ACCOUNT(USERNAME)
);

CREATE TABLE SPRING23_S003_7_USER(
    USERNAME VARCHAR(30) PRIMARY KEY,
    GENDER CHAR(1) CHECK (GENDER IN ('F', 'M')),
    REGISTRATION_DATE DATE,
    FOREIGN KEY (USERNAME) REFERENCES SPRING23_S003_7_ACCOUNT(USERNAME)
);

CREATE TABLE SPRING23_S003_7_BUYER(
    USERNAME VARCHAR(30) PRIMARY KEY,
    FOREIGN KEY (USERNAME) REFERENCES SPRING23_S003_7_USER(USERNAME) 
);

CREATE TABLE SPRING23_S003_7_SELLER(
    USERNAME VARCHAR(30) PRIMARY KEY,
    BIO VARCHAR(100),
    FOREIGN KEY (USERNAME) REFERENCES SPRING23_S003_7_USER(USERNAME) 
);

CREATE TABLE SPRING23_S003_7_PRODUCT_CATEGORY(
    CATEGORY_ID VARCHAR(10) PRIMARY KEY,
    CATEGORY_NAME VARCHAR(30)
);

CREATE TABLE SPRING23_S003_7_LISTING(
    LISTING_ID VARCHAR(10) PRIMARY KEY,
    NAME VARCHAR(30),
    DESCRIPTION VARCHAR(100),
    PRICE INT,
    CATEGORY_ID VARCHAR(10),
    SELLER_USERNAME VARCHAR(30),
    BUYER_USERNAME VARCHAR(30),
    BUY_DATE DATE,
    POST_DATE DATE,
    FOREIGN KEY (BUYER_USERNAME) REFERENCES SPRING23_S003_7_BUYER(USERNAME),
    FOREIGN KEY (SELLER_USERNAME) REFERENCES SPRING23_S003_7_SELLER(USERNAME),
    FOREIGN KEY (CATEGORY_ID) REFERENCES SPRING23_S003_7_PRODUCT_CATEGORY(CATEGORY_ID) 
);

CREATE TABLE SPRING23_S003_7_LISTING_PHOTOS(
    LISTING_ID VARCHAR(10) PRIMARY KEY,
    PHOTOS VARCHAR(50),
    FOREIGN KEY (LISTING_ID) REFERENCES SPRING23_S003_7_LISTING(LISTING_ID)
);

CREATE TABLE SPRING23_S003_7_REVIEW(
    REVIEW_ID VARCHAR(10) PRIMARY KEY,
    REVIEW VARCHAR(100),
    RATING INT CHECK (RATING IN (1,2,3,4,5)),
    SUCCESSFUL_TRANSACTION CHAR(1),
    LISTING_ID VARCHAR(10),
    REVIEWER_USERNAME VARCHAR(30),
    REVIEWEE_USERNAME VARCHAR(30),
    FOREIGN KEY (LISTING_ID) REFERENCES SPRING23_S003_7_LISTING(LISTING_ID),
    FOREIGN KEY (REVIEWER_USERNAME) REFERENCES SPRING23_S003_7_USER(USERNAME),
    FOREIGN KEY (REVIEWEE_USERNAME) REFERENCES SPRING23_S003_7_USER(USERNAME)
);

/*DURATION IN MONTHS */
CREATE TABLE SPRING23_S003_7_MEMBERSHIP_TYPE(
    TIER CHAR(10) PRIMARY KEY,
    DURATION CHAR(1),
    MAX_LISTINGS INT,
    PRICE INT
);

CREATE TABLE SPRING23_S003_7_MEMBERSHIP(
    USERNAME VARCHAR(30),
    MEMBERSHIP_ID VARCHAR(10),
    END_DATE DATE,
    TIER CHAR(10),
    PRIMARY KEY (USERNAME, MEMBERSHIP_ID),
    FOREIGN KEY (USERNAME) REFERENCES SPRING23_S003_7_SELLER(USERNAME),
    FOREIGN KEY (TIER) REFERENCES SPRING23_S003_7_MEMBERSHIP_TYPE(TIER)
);
